artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/079a2ac387a84957bdf31d08fd01b2f3/artifacts
end_time: 1714416972435
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 079a2ac387a84957bdf31d08fd01b2f3
run_name: Default
run_uuid: 079a2ac387a84957bdf31d08fd01b2f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1714416972418
status: 3
tags: []
user_id: mle-user
